### ISSUE TITLE
Change Original Layout

### ISSUE THREAD

**Issue by illemonati** [SheepTester/olamreee#34]
The line that exists in the beginning is very inconvenient. Please put elements in a more convenient location so one does not have to scroll that much.

**Comment by SheepTester** [comment]
It would be academically dishonest to make a new row where the IE drops again, yet more inconvenient if it was arranged in some other manner (eg making a new row at regular intervals regardless of IE - one would first have to reconstruct the rows in order to make the correct rows; it's also harder to see the trend of IE rising gradually and suddenly dropping)

**Comment by SheepTester** [comment]
meh
